/*
Newton Keyboard press and release codes
*/

#define keyPressed_ANSI_A              0x80
#define keyPressed_ANSI_S              0x81
#define keyPressed_ANSI_D              0x82
#define keyPressed_ANSI_F              0x83
#define keyPressed_ANSI_H              0x84
#define keyPressed_ANSI_G              0x85
#define keyPressed_ANSI_Z              0x86
#define keyPressed_ANSI_X              0x87
#define keyPressed_ANSI_C              0x88
#define keyPressed_ANSI_V              0x89
#define keyPressed_ANSI_B              0x8B
#define keyPressed_ANSI_Q              0x8C
#define keyPressed_ANSI_W              0x8D
#define keyPressed_ANSI_E              0x8E
#define keyPressed_ANSI_R              0x8F
#define keyPressed_ANSI_Y              0x90
#define keyPressed_ANSI_T              0x91
#define keyPressed_ANSI_1              0x92
#define keyPressed_ANSI_2              0x93
#define keyPressed_ANSI_3              0x94
#define keyPressed_ANSI_4              0x95
#define keyPressed_ANSI_6              0x96
#define keyPressed_ANSI_5              0x97
#define keyPressed_ANSI_Equal          0x98
#define keyPressed_ANSI_9              0x99
#define keyPressed_ANSI_7              0x9A
#define keyPressed_ANSI_Minus          0x9B
#define keyPressed_ANSI_8              0x9C
#define keyPressed_ANSI_0              0x9D
#define keyPressed_ANSI_RightBracket   0x9E
#define keyPressed_ANSI_O              0x9F
#define keyPressed_ANSI_U              0xA0
#define keyPressed_ANSI_LeftBracket    0xA1
#define keyPressed_ANSI_I              0xA2
#define keyPressed_ANSI_P              0xA3
#define keyPressed_ANSI_L              0xA5
#define keyPressed_ANSI_J              0xA6
#define keyPressed_ANSI_Quote          0xA7
#define keyPressed_ANSI_K              0xA8
#define keyPressed_ANSI_Semicolon      0xA9
#define keyPressed_ANSI_Backslash      0xAA
#define keyPressed_ANSI_Comma          0xAB
#define keyPressed_ANSI_Slash          0xAC
#define keyPressed_ANSI_N              0xAD
#define keyPressed_ANSI_M              0xAE
#define keyPressed_ANSI_Period         0xAF
#define keyPressed_ANSI_Grave          0xB2
#define keyPressed_ANSI_KeypadDecimal  0xC1
#define keyPressed_ANSI_KeypadMultiply 0xC3
#define keyPressed_ANSI_KeypadPlus     0xC5
#define keyPressed_ANSI_KeypadClear    0xC7
#define keyPressed_ANSI_KeypadDivide   0xCB
#define keyPressed_ANSI_KeypadEnter    0xCC
#define keyPressed_ANSI_KeypadMinus    0xCE
#define keyPressed_ANSI_KeypadEquals   0xD1
#define keyPressed_ANSI_Keypad0        0xD2
#define keyPressed_ANSI_Keypad1        0xD3
#define keyPressed_ANSI_Keypad2        0xD4
#define keyPressed_ANSI_Keypad3        0xD5
#define keyPressed_ANSI_Keypad4        0xD6
#define keyPressed_ANSI_Keypad5        0xD7
#define keyPressed_ANSI_Keypad6        0xD8
#define keyPressed_ANSI_Keypad7        0xD9
#define keyPressed_ANSI_Keypad8        0xDB
#define keyPressed_ANSI_Keypad9        0xDC

#define keyPressed_Return              0xA4
#define keyPressed_Tab                 0xB0
#define keyPressed_Space               0xB1
#define keyPressed_Delete              0xB3
#define keyPressed_Escape              0xB5
#define keyPressed_Command             0xB7
#define keyPressed_Shift               0xB8
#define keyPressed_CapsLock            0xB9
#define keyPressed_Option              0xBA
#define keyPressed_Control             0xBB
#define keyPressed_RightShift          0xBC
#define keyPressed_RightOption         0xBD
#define keyPressed_RightControl        0xBE
#define keyPressed_Function            0xBF
#define keyPressed_F17                 0xC0
#define keyPressed_VolumeUp            0xC8
#define keyPressed_VolumeDown          0xC9
#define keyPressed_Mute                0xCA
#define keyPressed_F18                 0xCF
#define keyPressed_F19                 0xD0
#define keyPressed_F20                 0xDA
#define keyPressed_F5                  0xE0
#define keyPressed_F6                  0xE1
#define keyPressed_F7                  0xE2
#define keyPressed_F3                  0xE3
#define keyPressed_F8                  0xE4
#define keyPressed_F9                  0xE5
#define keyPressed_F11                 0xE7
#define keyPressed_F13                 0xE9
#define keyPressed_F16                 0xEA
#define keyPressed_F14                 0xEB
#define keyPressed_F10                 0xED
#define keyPressed_F12                 0xEF
#define keyPressed_F15                 0xF1
#define keyPressed_Help                0xF2
#define keyPressed_Home                0xF3
#define keyPressed_PageUp              0xF4
#define keyPressed_ForwardDelete       0xF5
#define keyPressed_F4                  0xF6
#define keyPressed_End                 0xF7
#define keyPressed_F2                  0xF8
#define keyPressed_PageDown            0xF9
#define keyPressed_F1                  0xFA
#define keyPressed_LeftArrow           0xFB
#define keyPressed_RightArrow          0xFC
#define keyPressed_DownArrow           0xFD
#define keyPressed_UpArrow             0xFE

#define keyReleased_ANSI_A              0x00
#define keyReleased_ANSI_S              0x01
#define keyReleased_ANSI_D              0x02
#define keyReleased_ANSI_F              0x03
#define keyReleased_ANSI_H              0x04
#define keyReleased_ANSI_G              0x05
#define keyReleased_ANSI_Z              0x06
#define keyReleased_ANSI_X              0x07
#define keyReleased_ANSI_C              0x08
#define keyReleased_ANSI_V              0x09
#define keyReleased_ANSI_B              0x0B
#define keyReleased_ANSI_Q              0x0C
#define keyReleased_ANSI_W              0x0D
#define keyReleased_ANSI_E              0x0E
#define keyReleased_ANSI_R              0x0F
#define keyReleased_ANSI_Y              0x10
#define keyReleased_ANSI_T              0x11
#define keyReleased_ANSI_1              0x12
#define keyReleased_ANSI_2              0x13
#define keyReleased_ANSI_3              0x14
#define keyReleased_ANSI_4              0x15
#define keyReleased_ANSI_6              0x16
#define keyReleased_ANSI_5              0x17
#define keyReleased_ANSI_Equal          0x18
#define keyReleased_ANSI_9              0x19
#define keyReleased_ANSI_7              0x1A
#define keyReleased_ANSI_Minus          0x1B
#define keyReleased_ANSI_8              0x1C
#define keyReleased_ANSI_0              0x1D
#define keyReleased_ANSI_RightBracket   0x1E
#define keyReleased_ANSI_O              0x1F
#define keyReleased_ANSI_U              0x20
#define keyReleased_ANSI_LeftBracket    0x21
#define keyReleased_ANSI_I              0x22
#define keyReleased_ANSI_P              0x23
#define keyReleased_ANSI_L              0x25
#define keyReleased_ANSI_J              0x26
#define keyReleased_ANSI_Quote          0x27
#define keyReleased_ANSI_K              0x28
#define keyReleased_ANSI_Semicolon      0x29
#define keyReleased_ANSI_Backslash      0x2A
#define keyReleased_ANSI_Comma          0x2B
#define keyReleased_ANSI_Slash          0x2C
#define keyReleased_ANSI_N              0x2D
#define keyReleased_ANSI_M              0x2E
#define keyReleased_ANSI_Period         0x2F
#define keyReleased_ANSI_Grave          0x32
#define keyReleased_ANSI_KeypadDecimal  0x41
#define keyReleased_ANSI_KeypadMultiply 0x43
#define keyReleased_ANSI_KeypadPlus     0x45
#define keyReleased_ANSI_KeypadClear    0x47
#define keyReleased_ANSI_KeypadDivide   0x4B
#define keyReleased_ANSI_KeypadEnter    0x4C
#define keyReleased_ANSI_KeypadMinus    0x4E
#define keyReleased_ANSI_KeypadEquals   0x51
#define keyReleased_ANSI_Keypad0        0x52
#define keyReleased_ANSI_Keypad1        0x53
#define keyReleased_ANSI_Keypad2        0x54
#define keyReleased_ANSI_Keypad3        0x55
#define keyReleased_ANSI_Keypad4        0x56
#define keyReleased_ANSI_Keypad5        0x57
#define keyReleased_ANSI_Keypad6        0x58
#define keyReleased_ANSI_Keypad7        0x59
#define keyReleased_ANSI_Keypad8        0x5B
#define keyReleased_ANSI_Keypad9        0x5C

#define keyReleased_Return              0x24
#define keyReleased_Tab                 0x30
#define keyReleased_Space               0x31
#define keyReleased_Delete              0x33
#define keyReleased_Escape              0x35
#define keyReleased_Command             0x37
#define keyReleased_Shift               0x38
#define keyReleased_CapsLock            0x39
#define keyReleased_Option              0x3A
#define keyReleased_Control             0x3B
#define keyReleased_RightShift          0x3C
#define keyReleased_RightOption         0x3D
#define keyReleased_RightControl        0x3E
#define keyReleased_Function            0x3F
#define keyReleased_F17                 0x40
#define keyReleased_VolumeUp            0x48
#define keyReleased_VolumeDown          0x49
#define keyReleased_Mute                0x4A
#define keyReleased_F18                 0x4F
#define keyReleased_F19                 0x50
#define keyReleased_F20                 0x5A
#define keyReleased_F5                  0x60
#define keyReleased_F6                  0x61
#define keyReleased_F7                  0x62
#define keyReleased_F3                  0x63
#define keyReleased_F8                  0x64
#define keyReleased_F9                  0x65
#define keyReleased_F11                 0x67
#define keyReleased_F13                 0x69
#define keyReleased_F16                 0x6A
#define keyReleased_F14                 0x6B
#define keyReleased_F10                 0x6D
#define keyReleased_F12                 0x6F
#define keyReleased_F15                 0x71
#define keyReleased_Help                0x72
#define keyReleased_Home                0x73
#define keyReleased_PageUp              0x74
#define keyReleased_ForwardDelete       0x75
#define keyReleased_F4                  0x76
#define keyReleased_End                 0x77
#define keyReleased_F2                  0x78
#define keyReleased_PageDown            0x79
#define keyReleased_F1                  0x7A
#define keyReleased_LeftArrow           0x7B
#define keyReleased_RightArrow          0x7C
#define keyReleased_DownArrow           0x7D
#define keyReleased_UpArrow             0x7E